version: "3.8"
services:
  arch:
    container_name: arch
    image: "archlinux:latest"
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "2000-7000:2000-7000"
#      - 3000:3000
#      - 7173:7173
#      - 5268:5268
#      - 443:443
    volumes:
      - type: bind
        source: C:\
        target: /C:/
    networks:
      - db
networks:
  db:
    name: linuxconfig_db
    external: true
