#version: "3.8"
services:
  arch:
    container_name: arch
    image: "archlinux:latest"
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "3000-3200:3000-3200"
      - "7000-7200:7000-7200"
      - 443:443
    volumes:
      - type: bind
        source: C:\
        target: /C:/
    networks:
      - db
networks:
  db:
    name: workenvironment_db
    external: true
